# Generated by Django 5.0.6 on 2024-05-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Des', models.CharField(blank=True, max_length=100, null=True)),
                ('pri', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
        migrations.RenameField(
            model_name='formdb',
            old_name='Des',
            new_name='des',
        ),
    ]
