# Generated by Django 5.0.6 on 2024-05-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DecoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactdetails',
            new_name='contactdb',
        ),
    ]
